import { GalleryConfig } from '../types/gallery';

export const SAMPLE_GALLERIES: GalleryConfig[] = [
  {
    id: 'sample-kyoto-wanderlust',
    title: 'Kyoto & Tokyo Wanderlust',
    subtitle: 'Autumn expedition across Japanese temples, neon alleys, and bamboo groves',
    description: 'A curated collection of photography captured during our November trip through Kansai and Kanto regions. From the golden hour at Fushimi Inari to midnight reflections in Shinjuku.',
    creatorName: 'Elena Rostova',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    creatorEmail: 'elena.photography@example.com',
    createdAt: '2026-08-10T14:30:00.000Z',
    updatedAt: '2026-08-12T09:15:00.000Z',
    layout: 'masonry',
    theme: 'cinematic',
    columns: 3,
    enableDownload: true,
    showMetadata: true,
    coverPhotoId: 'sample-jp-1',
    photos: [
      {
        id: 'sample-jp-1',
        name: 'fushimi_inari_torii_gates.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Endless Vermilion Path',
        customCaption: 'Sunlight filtering through the thousand torii gates at Fushimi Inari Taisha early morning.',
        createdTime: '2026-08-01T06:45:00Z',
        size: '4820000',
        imageMediaMetadata: {
          width: 2400,
          height: 1600,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 35,
          aperture: 2.8,
          isoSpeed: 200,
          exposureTime: 0.004,
        },
      },
      {
        id: 'sample-jp-2',
        name: 'shinjuku_neon_rain.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Tokyo Cyberpunk Rain',
        customCaption: 'Vibrant neon reflections bouncing across the wet asphalt in Kabukicho.',
        createdTime: '2026-08-02T21:10:00Z',
        size: '5210000',
        imageMediaMetadata: {
          width: 1800,
          height: 2400,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 50,
          aperture: 1.8,
          isoSpeed: 800,
          exposureTime: 0.016,
        },
      },
      {
        id: 'sample-jp-3',
        name: 'mount_fuji_chureito_pagoda.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1578637387939-43c525550085?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Majestic Fuji & Pagoda',
        customCaption: 'Iconic panoramic viewpoint over Chureito Pagoda framing Mount Fuji at sunrise.',
        createdTime: '2026-08-03T05:30:00Z',
        size: '6100000',
        imageMediaMetadata: {
          width: 2500,
          height: 1667,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 24,
          aperture: 8.0,
          isoSpeed: 100,
          exposureTime: 0.02,
        },
      },
      {
        id: 'sample-jp-4',
        name: 'arashiyama_bamboo_forest.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Whispering Bamboo',
        customCaption: 'Soaring stalks of green creating natural cathedral arches in Arashiyama.',
        createdTime: '2026-08-04T07:15:00Z',
        size: '4950000',
        imageMediaMetadata: {
          width: 1800,
          height: 2400,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 16,
          aperture: 4.0,
          isoSpeed: 400,
          exposureTime: 0.008,
        },
      },
      {
        id: 'sample-jp-5',
        name: 'kinkaku_ji_golden_pavilion.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'The Golden Pavilion',
        customCaption: 'Mirror pond reflection of Kinkaku-ji illuminated by mid-day autumn sun.',
        createdTime: '2026-08-05T13:40:00Z',
        size: '5800000',
        imageMediaMetadata: {
          width: 2400,
          height: 1600,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 70,
          aperture: 5.6,
          isoSpeed: 160,
          exposureTime: 0.002,
        },
      },
      {
        id: 'sample-jp-6',
        name: 'traditional_tea_ceremony.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Art of Chanoyu',
        customCaption: 'A quiet afternoon preparing organic Uji matcha in a Gion tea house.',
        createdTime: '2026-08-06T15:20:00Z',
        size: '3900000',
        imageMediaMetadata: {
          width: 2200,
          height: 1467,
          cameraMake: 'Sony',
          cameraModel: 'A7 IV',
          focalLength: 50,
          aperture: 2.0,
          isoSpeed: 320,
          exposureTime: 0.01,
        },
      },
    ],
  },
  {
    id: 'sample-nordic-landscapes',
    title: 'Nordic Wilderness & Fjords',
    subtitle: 'Glacial lakes, volcanic ridges, and midnight sun across Scandinavia',
    description: 'An aerial and landscape visual journey through Lofoten islands and Western Norwegian fjords.',
    creatorName: 'Marcus Lindqvist',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    creatorEmail: 'marcus.photo@nordicexp.com',
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-08T10:00:00.000Z',
    layout: 'grid',
    theme: 'default',
    columns: 3,
    enableDownload: true,
    showMetadata: true,
    coverPhotoId: 'sample-nordic-1',
    photos: [
      {
        id: 'sample-nordic-1',
        name: 'reine_lofoten_mountains.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Lofoten Fishing Village',
        customCaption: 'Traditional red rorbu cabins nestled below towering sea cliffs in Reine.',
        createdTime: '2026-07-20T11:00:00Z',
        size: '5600000',
      },
      {
        id: 'sample-nordic-2',
        name: 'aurora_borealis_fjord.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Northern Lights Symphony',
        customCaption: 'Vivid green ribbons of the aurora dancing over calm coastal waters.',
        createdTime: '2026-07-21T23:45:00Z',
        size: '6400000',
      },
      {
        id: 'sample-nordic-3',
        name: 'emerald_glacial_lake.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Misty Dawn Valley',
        customCaption: 'Dense fog rolling through spruce forests surrounding the glacial basin.',
        createdTime: '2026-07-22T06:10:00Z',
        size: '4700000',
      },
      {
        id: 'sample-nordic-4',
        name: 'dramatic_coastal_highway.jpg',
        mimeType: 'image/jpeg',
        directUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600&auto=format&fit=crop',
        customTitle: 'Ocean Road Crossing',
        customCaption: 'The winding Atlantic Road connecting archipelago islets.',
        createdTime: '2026-07-23T14:20:00Z',
        size: '5100000',
      },
    ],
  },
];
